[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python", "uv"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
# language-servers = ["pyright", "ruff"]
# language-servers = ["basedpyright", "ruff"]

language-servers = ["ty", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

# [language.formatter]
# command = "black"
# args = [
#   "-",
#   "--quiet",
#   "--line-length=88"
# ]

# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"]


# [language-server.pyright.config]
# reportMissingTypeStubs = false
# inlay-hints = true

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"
# autoImportCompletions = true


# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]

# [language-server.basedpyright.config]
# basedpyright.analysis.diagnosticMode = "openFilesOnly"
# basedpyright.analysis.typeCheckingMode = "standard"


[language-server.ruff]
command = "ruff"
args = ["server"]

# [language-server.ruff.config]
# settings = {args = []}

[language-server.ruff.config.settings]
lineLength = 80

[language-server.ruff.config.settings.lint]
select = ["E4", "E7"]
preview = false

[language-server.ruff.config.settings.format]
preview = true
